version: 2.0

sources:
  - name: dwblackfriday  # Substitua pelo nome do banco de dados
    schema: public   # Substitua pelo nome do schema

    tables:
      - name: typeform_responses
        description: "Responses from Typeform surveys."
        columns:
          - name: "submitted_at"
            description: "The date and time when the response was submitted."
          - name: "response_id"
            description: "Unique identifier for the response."
          - name: "dce81f19-377a-4b83-8824-5bd5be2b8d17	"
            description: "Response to question 1."
          - name: "0bd30d70-8cdb-480a-ac1c-132973e15e56"
            description: "Response to question 2."
          - name: "c558e6cd-564c-4918-9591-69ab45f40aef	"
            description: "Response to question 3."
          - name: "e3f207ce-7da0-4fc6-86a5-e6728b00a038"
            description: "Response to question 4."

      - name: google_analytics_data
        description: "Google Analytics data for the website."
        columns:
          - name: "date"
            description: "The date of the session."
          - name: "city"
            description: "The city of the user."
          - name: "country"
            description: "The country of the user."
          - name: "deviceCategory"
            description: "The category of device used (desktop, mobile, etc.)."
          - name: "sessionSource"
            description: "The source of the session (e.g., youtube.com, direct)."
          - name: "sessionMedium"
            description: "The medium of the session (e.g., referral, organic)."
          - name: "totalUsers"
            description: "The total number of users in the session."
          - name: "newUsers"
            description: "The number of new users in the session."
          - name: "activeUsers"
            description: "The number of active users in the session."
          - name: "sessions"
            description: "The total number of sessions."
          - name: "engagedSessions"
            description: "The number of engaged sessions."
          - name: "averageSessionDuration"
            description: "The average duration of the session."
          - name: "screenPageViews"
            description: "The number of page views."